---
name: get name

on:
  # push:
  #   branches:
  #     - master
  workflow_dispatch:

jobs:
  get_name:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
    - name: echo
      run: | 
        echo "hello"
    - name: send notification
      uses: act10ns/slack@v1
      with:
        status: ${{job.status}}
        steps: ${{toJson(steps)}}
      if: always()
    # - name: Download Artifact
    #   uses: actions/download-artifact@v2
    #   with:
    #       name: my-text-artifact
    #       path: temp.txt
    
    # - name: Read Deployment ID
    #   id: read_deployment_id
    #   run: |
    #     tmp_id=$(cat temp.txt)
    #     echo "tmp id: $tmp_id"
