---
name: get name

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  get_name:
    runs-on: ubuntu-latest
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
          name: my-text-artifact
          path: temp.txt
    
    - name: Read Deployment ID
      id: read_deployment_id
      run: |
        tmp_id=$(cat temp.txt)
        echo "tmp id: $tmp_id"