---
name: get name

on:
  # push:
  #   branches:
  #     - master
  workflow_dispatch:

jobs:
  get_name:
    runs-on: ubuntu-latest
    steps:
    # - name: create log file
    #   run: touch hello.txt
    - name: generate logs
      run: |
        echo rohit
        echo jigyasa
        >> hello.txt

    - name: generate logs2
      run: |
        echo saini
        echo saini
        >> hello.txt
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET }}
        aws-region: ap-south-1
        
    - name: Push Logs to S3
      run: aws s3 cp hello.txt s3://salesforce-murli/qa/hello.txt
    # - name: set variable
    #   run: |
    #     exit_code=0
    #     if [ $exit_code -ne 0 ]; then
    #         echo "Script failed with exit code $exit_code"
    #         exit $exit_code
    #     fi
    # - name: run after error
    #   if: always()
    #   run: |
    #     echo "hello"
    # - name: print name
    #   run: |
    #     echo "sdgzdsgvzsbgzgbz" >> log.txt
    #     echo "esgzdsgzdgbzg" >> log.txt
    # - name: print log
    #   run: cat log.txt
    # - name: Download Artifact
    #   uses: actions/download-artifact@v2
    #   with:
    #       name: my-text-artifact
    #       path: name.txt
    
    # - name: Read Deployment ID
    #   id: read_deployment_id
    #   run: |
    #     tmp_id=$(cat name.txt)
    #     echo "tmp id: $tmp_id"
    # - uses: actions/checkout@v3
    # - name: download artifact
    #   env:
    #     GH_TOKEN: ${{ github.token }}
    #   run: gh run download --name my-text-artifact
