---
name: print name

on: 
  pull_request:
    branches:
    - master
  workflow_dispatch:

jobs:
  print_name:
    runs-on: ubuntu-latest
    steps:
    - name: Create txt file
      run: echo "rohit" > temp.txt
      
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-text-artifact
        path: temp.txt