---
name: print name

on: 
  pull_request:
    branches:
    - master
  workflow_dispatch:

jobs:
  print_name:
    runs-on: ubuntu-latest
    steps:
    - name: print name
      run: echo "Hello Rohit"