---
name: print name

on: 
  # pull_request:
  #   branches:
  #   - master
  workflow_dispatch:

jobs:
  print_name:
    runs-on: ubuntu-latest
    steps:
    # - name: Create txt file
    #   run: echo "rohit" > name.txt

    # - name: Upload artifact
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: my-text-artifact
    #     path: name.txt
    - name: print repo name
      run: |
        echo "hello ${{ env.DEPLOYID_BRANCH_NAME }}"
        BASE64_AZ_DEVOPS_PATH=$(echo -n ${{ env.DEPLOYID_BRANCH_NAME }} | base64)
        echo "BASE64_AZ_DEVOPS_PATH=$BASE64_AZ_DEVOPS_PATH" >> $GITHUB_ENV
    - name: echo
      run: echo $BASE64_AZ_DEVOPS_PATH
      
    # - name: Checkout code
    #   uses: actions/checkout@v2

    # - name: run github client
    #   env:
    #     GH_TOKEN: ${{ github.token }}
    #   run: gh variable set DEPLOYID_BRANCH_NAM --body "Set from workflow"
