---
name: print name

on: 
  pull_request:
    branches:
    - master
  workflow_dispatch:

jobs:
  print_name:
    runs-on: ubuntu-latest
    steps:
    # - name: Create txt file
    #   run: echo "rohit" > name.txt

    # - name: Upload artifact
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: my-text-artifact
    #     path: name.txt
    - name: print repo name
      run: echo "$github.event.repository.name"
      
    - name: Checkout code
      uses: actions/checkout@v2

    - name: run github client
      env:
        GH_TOKEN: ${{ github.token }}
      run: gh variable set DEPLOYID_BRANCH_NAM --body "Set from workflow"
