name: snowflake-devops-demo

# Controls when the action will run. 
on:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'migrations/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Python 3.8.x
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8.x
      - name: Install Dependencies
        run: |
          pip install snowflake-connector-python

      - name: Run schemachange
        env:
          SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SF_ROLE: ${{ secrets.SF_ROLE }}
          SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
          SF_DATABASE: ${{ secrets.SF_DATABASE }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
          SF_SCHEMA: ${{ secrets.SF_SCHEMA }}
        run: |
          INSERT_QUERY="INSERT INTO your_table (NAME,PASSWORD) VALUES ('piyush', 'admin');"

          # Create a temporary file to store the SQL query
          SQL_FILE=$(mktemp)
          echo "$INSERT_QUERY" > "$SQL_FILE"

          # Use curl to execute the query using the Snowflake REST API
          curl -X POST \
            --url "https://$SF_ACCOUNT.snowflakecomputing.com/v1/query-request?warehouse=$SF_WAREHOUSE&database=$SF_DATABASE&schema=$SF_SCHEMA" \
            --header "Content-Type: application/json" \
            --data-raw "{\"sqlText\": \"$(cat $SQL_FILE | jq -s -R -r @uri)\", \"binds\": []}" \
            --user "$SF_USERNAME:$SNOWFLAKE_PASSWORD"

          # Clean up the temporary file
          rm "$SQL_FILE"
          # python $GITHUB_WORKSPACE/scripts/snowflake_insert.py
          # echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          # python --version
          # echo "Step 1: Installing schemachange"
          # pip install schemachange
          
          # echo "Step 2: Running schemachange"
          # schemachange -f $GITHUB_WORKSPACE/migrations -a $SF_ACCOUNT -u $SF_USERNAME -r $SF_ROLE -w $SF_WAREHOUSE -d $SF_DATABASE -c $SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table
